import { Context } from 'koishi'
import { } from 'koishi-plugin-markdown-to-image-service'

export type FormatType = 'json' | 'yaml' | 'toml'

export async function renderMarkdownImage(
  ctx: Context,
  formattedData: string,
  format: FormatType,
  messageMode: 'forward' | 'image',
): Promise<Buffer> {
  const formatName = format.toUpperCase()
  const timestamp = new Date().toLocaleString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  })

  // markdown 代码块要顶格
  const markdown = `<style>
pre code {
  font-size: 18px !important;
  line-height: 1.3 !important;
}
</style>

# Quote Message Debug (${formatName})

\`\`\`${format}
${formattedData}
\`\`\`

---

> **Generated by** koishi-plugin-quote-debug-msg-json-image  
> **Mode:** ${messageMode} · markdown image  
> **Time:** ${timestamp}`

  return ctx.markdownToImage.convertToImage(markdown)
}
